# Generated by Django 5.0.2 on 2024-02-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produits',
        ),
    ]
