# Generated by Django 5.0.2 on 2024-02-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_fournisseur_produits_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
