# Generated by Django 5.0.2 on 2024-04-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_alter_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='img',
            field=models.ImageField(blank='True', upload_to=''),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.produits')),
            ],
        ),
    ]
